dist: xenial
sudo: true
python: 3.7

before_install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-setuptools python3-pip ninja-build make -y
  - sudo pip3 install meson
  - sudo apt-get install libusb-dev libusb-1.0-0-dev libglfw3-dev libglew-dev -y

language: cpp
compiler:
  - gcc

script:
  - meson builddir
  - ninja -C builddir